name: Deploy to Render

on:
  push:
    branches:
      - main  # Esto ejecutará el deploy cada vez que se haga push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Aquí defines la versión de Node.js que usarás

      - name: Install dependencies
        run: npm install

      - name: Render Deployment
        run: |
          # Esto ejecuta el comando de despliegue de Render.
          # Para hacer esto funcionar, necesitas tener el CLI de Render instalado y configurado.
          # Asegúrate de seguir las instrucciones de Render para obtener tu token de autenticación y configurar el CLI.
          curl -sSL https://cli.render.com/install | sh
          render login --token ${{ secrets.RENDER_API_TOKEN }}
          render deploy
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}  # Guarda tu token de Render en los secretos de GitHub


